// Generated by https://quicktype.io

export type ExtWithLinks = {
  name: string
  msmarketplaceUrl: string
  openvsx: string
  repoUrl: string | null
  licence: null | string
}

export type VSExtension = ExtWithLinks & {
  lastUpdated: string
  licenceUrl: null | string
}

export type ExtensionNotFound = {
  publisherName: string
  name: string
  notFound: boolean
}

export interface OpenVsxExtension {
  namespaceUrl: string
  reviewsUrl: string
  files: Files
  name: string
  namespace: string
  version: string
  publishedBy: PublishedBy
  unrelatedPublisher: boolean
  namespaceAccess: string
  allVersions: { [key: string]: string }
  downloadCount: number
  reviewCount: number
  versionAlias: string[]
  timestamp: string
  preview: boolean
  displayName: string
  description: string
  engines: Engines
  categories: string[]
  tags: string[]
  license: string
  repository: string
  bugs: string
  qna: string
  dependencies: any[]
  bundledExtensions: any[]
}

export interface Engines {
  vscode: string
}

export interface Files {
  icon: string
  license: string
  changelog: string
  readme: string
  manifest: string
  download: string
}

export interface PublishedBy {
  loginName: string
  fullName: string
  avatarUrl: string
  homepage: string
  provider: string
}
